project:
  type: book

book:
  title: "Introdução ao Rmarkdown e Quarto"
  author:
    - name: "Ricardo de Oliveira Perdiz"
      orcid: "https://orcid.org/0000-0002-2333-6549"
      email: ricoperdiz@gmail.com
      affiliation:
        - name: "Pós-doutorando no Programa de pós-graduação em Recursos Naturais (PRONAT), Universidade Federal de Roraima (UFRR)"
          city: Boa Vista
          state: RR
          url: "https://www.ricardoperdiz.com/"
  date: last-modified
  date-format: "[Última atualização:] DD/MMM/YYYY"
  cover-image: "figuras/capa.png"
  chapters:
    - index.qmd
    - part: "Introdução ao Rmarkdown"
      chapters:
        - 01_instalacao.qmd
        - 02_basico.qmd
        - 03_sintaxe.qmd
        - 04_compilacao.qmd
    - part: "Introdução ao Quarto"
      chapters: 
        - 0_quarto.qmd
    - exemplos.qmd
    - referencias.qmd
    # - docx.qmd
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: "figuras/favicon.png"
  open-graph: true
  twitter-card:
    title: "Introdução ao Rmarkdown e Quarto"
    description: "Material sobre o uso de Rmarkdown e Quarto para a produção de relatórios, apresentações, artigos, livros e diversos outros produtos."
    image: "figuras/capa.png"
    creator: "ricoperdiz"
    site: "ricoperdiz"
  site-url: "https://intrormarkdown.netlify.app/"
  # repo-url: https://github.com/ricoperdiz/curso_rmarkdown/
  # repo-actions: [edit, issue]
  # issue-url: https://github.com/ricoperdiz/curso_rmarkdown/issues
  # Search tools
  search:
    location: sidebar
    type: textbox
  # Sidebar tools:
  sidebar:
    style: "docked"
    search: true
    collapse-level: 3
    tools:
      - icon: github
        menu:
          - text: Código fonte do livro
            href: https://github.com/ricoperdiz/curso_rmarkdown
          - text: Reporte um problema
            href: https://github.com/ricoperdiz/curso_rmarkdown/issues
          - text: Deixe seu comentário
            href: https://github.com/ricoperdiz/curso_rmarkdown/discussions
  page-footer:
    center:
      - text: "Licença"
        href: https://github.com/ricoperdiz/curso_rmarkdown?tab=CC-BY-4.0-1-ov-file#readme
      - text: "Perguntas frequentes"
        href: perguntas_frequentes.qmd
    right:
      - icon: github
        href: https://github.com/ricoperdiz/curso_rmarkdown/
  sharing: [twitter, facebook]
  comments:
    giscus:
      repo: ricoperdiz/curso_rmarkdown
      category: "Announcements"
      mapping: title
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme:
        light: "light"
        dark: "dark_dimmed"
      language: pt
      # strict: true

encoding: "UTF-8"
lang: pt
language: 
  search-box-placeholder: Busque aqui

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

knitr:
  opts_knit:
    verbose: true

citation: true
bibliography: 
  - bib/bib.bib
  - bib/pkg-bib.bib

format:
  html:
    # toc: true
    # toc-depth: 3
    # toc-expand: 2
    # toc-title: "Conteúdo"
    # toc-location: left
    number-sections: false
    # number-depth: 1
    fontsize: 1.1em
    theme: 
      light: zephyr
      dark: darkly
    code-copy: "hover"
    code-overflow: wrap

# editor: visual

