---
title: "Modelos de arquivos"
---

```{r}
#| include: false
source("R/utils.R")
```

Disponibilizo abaixo alguns arquivos Rmd que podem auxiliar você a produzir documentos contendo mapas, tabelas e outros, por meio de códigos em R.
Pretendo disponibilizar arquivos variados para que eles possam ser mesclados e ajudar o praticante iniciante na produção do que ele desejar.  

## Análise exploratória de dados - Conjunto de dados `iris`

Disponível em: [/docs/exemplos/aed_iris.Rmd](/docs/exemplos/aed_iris.Rmd).  

`r import_example("aed_iris.Rmd")`

## Mapa interativo com pacote `leaflet`

Disponível em: [/docs/exemplos/mapa1.Rmd](/docs/exemplos/mapa1.Rmd).  

`r import_example("mapa1.Rmd")`

## Referência cruzada em figuras e tabelas

Disponível em: [/docs/exemplos/referencia_cruzada.Rmd](/docs/exemplos/referencia_cruzada.Rmd).  

`r import_example("referencia_cruzada.Rmd")`

## Aparência

Disponível em: [/docs/exemplos/aparencia.Rmd](/docs/exemplos/aparencia.Rmd).  

`r import_example("aparencia.Rmd")`

## Controle de figuras

Disponível em: [/docs/exemplos/controle_figuras.Rmd](/docs/exemplos/controle_figuras.Rmd).  

`r import_example("controle_figuras.Rmd")`

## Referências bib

Disponível em: [/docs/exemplos/minhaprimeiralistadereferencia.Rmd](/docs/exemplos/minhaprimeiralistadereferencia.Rmd).  

`r import_example("minhaprimeiralistadereferencia.Rmd")`

Você pode baixar também um arquivo `.bib` como exemplo.
Construímos este arquivo em sala de aula:

+ [/docs/exemplos/minhaprimeiraref.bib](/docs/exemplos/minhaprimeiraref.bib)  

Temos também um arquivo `csl` com normas da ABNT. Baixe-o por meio do endereço abaixo:

+ [/docs/exemplos/associacao-brasileira-de-normas-tecnicas.csl](/docs/exemplos/associacao-brasileira-de-normas-tecnicas.csl)  

